--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/OguzhanUmutlu/BuyKeepInventory
build-by-default: true
branches:
- main
projects:
  BuyKeepInventory:
    path: ""
    icon: "icon.png"
    lint:
      phpstan: false
...
